[package]
name = "outfit"
version = "0.1.0"
edition = "2021"

[dependencies]
aberth = { version = "0.4.1", default-features = false }
ahash = { version = "0.8.11", default-features = false }
arrow-array = { version = "54.3.1", default-features = false }
camino = { version = "1.1.9", default-features = false }
csv = { version = "1.3.1", default-features = false }
directories = "6.0.0"
hifitime = { version = "4.0.2", default-features = false, features = [
    "ut1",
    "std",
] }
itertools = { version = "0.14.0", default-features = false, features = [
    "use_std",
] }
nalgebra = { version = "0.33.2" }
ordered-float = { version = "5.0.0", default-features = false }
parquet = { version = "54.2.1", default-features = false, features = [
    "arrow",
    "snap",
] }
quick-xml = { version = "0.37.3", features = [
    "serialize",
], default-features = false }
regex = { version = "1.11.1", default-features = false }
serde = { version = "1.0", features = ["derive"], default-features = false }
smallvec = { version = "1.14.0", default-features = false }
thiserror = { version = "2.0.12", default-features = false }
ureq = { version = "3.0.10", default-features = false, features = ["rustls"] }
nom = { version = "8.0.0" }
once_cell = { version = "1.21.3", default-features = false }
roots = { version = "0.0.8", default-features = false }
rand = { version = "0.9.2", default-features = false, features = ["std_rng"] }
rand_distr = { version = "0.5.1", default-features = false }

reqwest = { version = "0.12.15", default-features = false, optional = true, features = [
    "stream",
] }
tokio = { version = "1.44.1", default-features = false, optional = true, features = [
    "fs",
    "rt",
    "rt-multi-thread",
] }
tokio-stream = { version = "0.1.17", default-features = false, optional = true }

[dev-dependencies]
approx = { version = "0.5.1", default-features = false }
criterion = { version = "0.5.1", default-features = false }
husky-rs = "0.1.5"
proptest = "1.7.0"

[features]
jpl-download = ["dep:reqwest", "dep:tokio", "dep:tokio-stream"]

[[bench]]
name = "load_parquet"
harness = false

[profile.release]
debug = true

[profile.dev.package."*"]
debug = false
