name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    name: Test Outfit
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Deux variantes: sans feature et avec jpl-download
        include:
          - name: Default features
            features: ""
          - name: With jpl-download feature
            features: "--features jpl-download"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run tests (${{ matrix.name }})
        run: |
          echo "Running cargo test with features: '${{ matrix.features }}'"
          cargo test --locked --all-targets ${{ matrix.features }}
